# Generated by Django 5.2.7 on 2025-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingkey',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles to assign when user completes onboarding', to='users.role'),
        ),
    ]
