# Generated by Django 5.2.7 on 2025-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firm_role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
    ]
