# Generated by Django 5.2.7 on 2025-10-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Discovery', 'Negotiation'", max_length=100
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="The step number (1, 2, 3...)"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CaseWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Litigation', 'Contract Review'",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_cases",
                to="cases.casestage",
            ),
        ),
        migrations.AddField(
            model_name="casestage",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="cases.caseworkflow",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.caseworkflow",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casestage",
            unique_together={("workflow", "order")},
        ),
    ]
