# Generated by Django 5.2.7 on 2025-10-19 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_timeentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Real Estate Closing Contract'", max_length=255
                    ),
                ),
                ("template_file", models.FileField(upload_to="document_templates/")),
                ("is_public", models.BooleanField(default=False)),
                (
                    "context_fields",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of placeholder fields this template uses.",
                        null=True,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
