# Generated by Django 5.2.7 on 2025-10-20 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_invoice_invoiceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("timestamp_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_logs",
                        to="cases.case",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="cases.casestage",
                    ),
                ),
            ],
        ),
    ]
