# Generated by Django 5.2.7 on 2025-11-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_casestagelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="time_entry",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
    ]
