# Generated by Django 5.2.7 on 2025-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_consultationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
